export const appImages = {
    splash: require('../../assets/splash.png'),
    logo: require('../../assets/logo.png'),
    backgroundStartPage: require('../../assets/startPageBackgroundImage.png'),
    dishStub: require('../../assets/stub.png'),
    geoEnter: require('../../assets/geo_enter.png'),
    checkActive: require('../../assets/check_active.png'),
    arrow: require('../../assets/arrow.png'),
    geo: require('../../assets/geo.png'),
    search: require('../../assets/search.png'),
    restActive: require('../../assets/rest_active.png'),
    basketBigStock: require('../../assets/basket_big_stock.png'),
    clock: require('../../assets/clock.png'),
    courier: require('../../assets/courier.png'),
    receipt: require('../../assets/receipt.png'),
    ruble: require('../../assets/ruble.png'),
    restInactive: require('../../assets/rest_inactive.png'),
    basketActive: require('../../assets/basket_active.png'),
    basketInactive: require('../../assets/basket_inactive.png'),
    promotionActive: require('../../assets/promotion_active.png'),
    promotionsInactive: require('../../assets/promotion_inactive.png'),
    userInactive: require('../../assets/user_inactive.png'),
    userActive: require('../../assets/user_active.png'),
    plus: require('../../assets/plus.png'),
    minus: require('../../assets/minus.png'),
    times: require('../../assets/times.png')
}